PL/Controllers/TareaController.cs
using DL.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace PL.Controllers
{
    public class TareaController : Controller
    {
        private readonly IConfiguration _configuration;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly BL.Status _status;
        public TareaController(IConfiguration configuration, IHttpClientFactory httpClientFactory, BL.Status status)
        {
            _configuration = configuration;
            _httpClientFactory = httpClientFactory;
            _status = status;
            _status = status;
        }

        [HttpGet]
        public IActionResult GetAll()
        {
            ML.Tarea tarea = new ML.Tarea();

            ML.Result result = GetAllApi();

            if (result.Correct)
            {
                tarea.Tareas=result.Objects;
            }
            else
            {
                tarea.Tareas = new List<object>();
            }
                return View(tarea);
        }
        [HttpGet]
        public IActionResult Formulario(int? IdTarea)
        {
            ML.Tarea tarea = new ML.Tarea();
            tarea.Status =new ML.Status();
            ML.Result resultStatus=_status.GetAll();
            if (resultStatus.Correct)
            {
                tarea.Status.Statuses=resultStatus.Objects;
            }
            else
            {
                tarea.Status.Statuses = new List<object>();
            }
            if (IdTarea ==0)
            {
                
            }
            else if (IdTarea > 0)
            {
                ML.Result result = GetByIdWebAPI(IdTarea.Value);
                if (result.Correct)
                {
                    tarea = (ML.Tarea)result.Object;
                    tarea.Status.Statuses = resultStatus.Objects;
                }
            }
            return View(tarea);
        }
        [HttpPost]
        public IActionResult Formulario(ML.Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                ML.Result result = new ML.Result();

                if (tarea.IdTarea == 0)
                {
                    result = AddApi(tarea);
                    TempData["Mensaje"] = "Tarea agregada correctamente.";
                }
                else
                {
                    result = UpdateApi(tarea);
                    TempData["Mensaje"] = "Tarea actualizada correctamente.";
                }
                if (result.Correct)
                {
                    TempData.Keep("Mensaje");
                    return RedirectToAction("GetAll");
                }
            }
            else
            {
                tarea.Status.Statuses = new List<object>();
                return View(tarea);
            }
                return View();
        }
        public ActionResult Delete(int IdTarea)
        {
            ML.Result result = DeleteApi(IdTarea);
            if (result.Correct)
            {
                TempData["Mensaje"] = "Tarea eliminada correctamente.";
                return RedirectToAction("GetAll");
            }
            else
            {
                TempData["Mensaje"] = "No se pudo eliminar";
                return View("Error");
            }

        }


        public ML.Result GetAllApi()
        {
            ML.Result result = new ML.Result();
            result.Objects = new List<object>();

            using (var client = new HttpClient())
            {
                var endpoint = _configuration["EndpointsApi:GetAll"];
                var responseTask = client.GetAsync(endpoint);

                responseTask.Wait();

                var resultTask = responseTask.Result;

                if (resultTask.IsSuccessStatusCode)
                {
                    var readTask = resultTask.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)

                    {

                        ML.Tarea resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Tarea>(resultItem.ToString());

                        result.Objects.Add(resultItemList);

                    }

                    result.Correct = true;
                }
                else
                {
                    result.Correct = false;
                    result.ErrorMessage = "No se pudieron obtener las tareas desde la API.";
                }
            }

            return result;
        }
        public ML.Result GetByIdWebAPI(int IdTarea)
        {
            ML.Result result = new ML.Result();

            try
            {
                var endpoint = _configuration["EndpointsApi:GetById"];

                using (var client = new HttpClient())
                {

                    var urlCompleta = $"{endpoint}={IdTarea}";
                    var responseTask = client.GetAsync(urlCompleta);

                    responseTask.Wait();
                    var resultAPI = responseTask.Result;

                    if (resultAPI.IsSuccessStatusCode)
                    {
                        var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();

                        ML.Tarea resultItemList = new ML.Tarea();
                        resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Tarea>(readTask.Result.Object.ToString());
                        result.Object = resultItemList;

                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                        result.ErrorMessage = "No existen registros en la tabla Departamento";
                    }
                }
            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;
            }
            return result;
        }
        public ML.Result DeleteApi(int IdTarea)
        {

            ML.Result result = new ML.Result();

            try
            {
                var endpoint = _configuration["EndpointsApi:Delete"];
                using (var client = new HttpClient())
                {

                    var urlCompleta = $"{endpoint}={IdTarea}";
                    var responseTask = client.DeleteAsync(urlCompleta);
                    responseTask.Wait();

                    var resultApi = responseTask.Result;
                    if (resultApi.IsSuccessStatusCode)
                    {
                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                        result.ErrorMessage = "No se pudo eliminar";
                    }
                }
            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;
            }                  
            return result;
        }
        public ML.Result AddApi(ML.Tarea tarea)
        {
            ML.Result result = new ML.Result();
            try
            {
                var endpoint = _configuration["EndpointsApi:Create"];

                using (var client = new HttpClient())
                {
                    
                    var responseTask = client.PostAsJsonAsync<ML.Tarea>(endpoint,tarea);
                    responseTask.Wait();

                    var resultApi = responseTask.Result;

                    if (resultApi.IsSuccessStatusCode)
                    {
                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                        result.ErrorMessage = "No se pudo agregar";
                    }
                }
            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;
            }
            return result;
        }


        public ML.Result UpdateApi(ML.Tarea tarea)
        {
            ML.Result result= new ML.Result();
            try
            {
                using (var client = new HttpClient())
                {
                    var endpoint = _configuration["EndpointsApi:Update"];
                    var responseTask = client.PutAsJsonAsync<ML.Tarea>(endpoint, tarea);
                    responseTask.Wait();

                    var resultApi = responseTask.Result;

                    if (resultApi.IsSuccessStatusCode)
                    {
                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                        result.ErrorMessage = "No se pudo actualizar";
                    }
                }
            }
            catch (Exception ex)
            {
                result.Correct = false;
                result.ErrorMessage = ex.Message;
            }
            
            return result;
        }
    }

}

PL/Views/Tarea/Formulario.cshtml
@model ML.Tarea
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>Gestion de Tareas</h2>
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            <h5>Agregar nueva tarea</h5>
        </div>
    </div>
    @using (Html.BeginForm("Formulario", "Tarea", FormMethod.Post, new { enctype = "multipart/form-data", @class = "needs-validation", @novalidate = "novalidate" }))
    {
        <div class="row">
            <div class="col-12">
                <div class="row">
                    
                        @Html.HiddenFor(model => model.IdTarea)
                    
                    <div class="col-6">
                        @Html.LabelFor(model => model.Title, new { @class = "form-label"  })
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="bi bi-list-task"></i>
                            </div>
                            @Html.TextBoxFor(model => model.Title, new { @class = "form-control", @required = "required" })
                        </div>
                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.Description, new { @class = "form-label" })
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="bi bi-list-task"></i>
                            </div>
                            @Html.TextBoxFor(model => model.Description, new { @class = "form-control", @required = "required" })
                        </div>
                    </div>
                </div>
                <div class="row mt-3">                 
                    <div class="col-6">
                        @Html.LabelFor(model => model.CreationDate, new { @class = "form-label" })
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="bi bi-calendar-check"></i>
                            </div>
                           @if (Model.CreationDate.HasValue)
                           {
                                @Html.TextBoxFor(model => model.CreationDate, "{0:yyyy-MM-ddTHH:mm}", new { @class = "form-control", type = "datetime-local", @required = "required" })
                           }
                           else
                           {
                                @Html.TextBoxFor(model => model.CreationDate, DateTime.Now.ToString("yyyy-MM-ddTHH:mm"), new { @class = "form-control", type = "datetime-local" })
                           }

                        </div>
                    </div>
                    <div class="col-6">
                        @Html.LabelFor(model => model.Status, new { @class = "form-label" })
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <i class="bi bi-list" style="font-size: 1em;"></i>
                            </div>
                            @Html.DropDownListFor(model => model.Status.IdStatus, new SelectList(Model.Status.Statuses, "IdStatus", "Nombre"),
                            "Selecciona un status", new { @id = "ddlStatus", @class = "form-control", @required = "required" })
                        </div>
                    </div>
                </div>              
                <div class="row mt-3">
                    <div class="col-2">
                        <input type="submit" name="Action" value="Guardar" class="btn btn-success" />
                    </div>
                    <div class="col-2">
                        @Html.ActionLink("Regresar", "GetAll", "Auto", new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>

        </div>

    }

</div>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/js/Validaciones/ValidacionesTarea.js"></script>

PL/Views/Tarea/GetAll.cshtml
@model ML.Tarea
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@if (TempData["Mensaje"] != null)
{
    <script>
        alert('@TempData["Mensaje"]');
    </script>
}

<h2>Gestion de Tareas</h2>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            @Html.ActionLink("Agregar Tarea", "Formulario", "Tarea", new { IdTarea = 0 }, new { @class = "btn btn-success" })
        </div>
    </div>

    <div class="row">
        <div class="col-12">
            @if (Model.Tareas != null)
            {
                <table class="table table-hover table-responsive-lg">
                    <thead>
                        <tr>
                            <th> Editar </th>
                            <th> IdTarea </th>
                            <th> Titulo </th>
                            <th> Descripcion </th>
                            <th> Status </th>
                            <th> Fecha </th>
                            <th> Eliminar </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Tarea tarea in Model.Tareas)
                        {
                            <tr>
                                <td>

                                    <a href="@Url.Action("Formulario", "Tarea", new { IdTarea = tarea.IdTarea })"> 
                                        <i class="bi bi-pencil-square"></i>
                                    </a>

                                </td>
                                <td>@tarea.IdTarea</td>
                                <td>@tarea.Title</td>
                                <td>@tarea.Description</td>
                                <td>@tarea.Status.Nombre</td>
                                <td>
                                    @if (tarea.CreationDate.HasValue)
                                    {
                                        @tarea.CreationDate.Value.ToString("dd/MM/yyyy HH:mm")
                                    }
                                    else
                                    {
                                        <text>Sin fecha</text>
                                    }
                                </td>
                                <td>
                                    <a href="@Url.Action("Delete", "Tarea", new { IdTarea = tarea.IdTarea })">
                                        <i class="bi bi-trash-fill"></i>
                                    </a>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            }
            else
            {
                <div class="alert alert-danger" role="alert">
                    No hay registros
                </div>
            }

        </div>
    </div>

</div>